#!/usr/bin/expect

set folder ""
switch -- [llength $argv] {
    2 {
        set user [lindex $argv 1]
        set text [lindex $argv 2]
    }
    3 {
        set folder [lindex $argv 0]
        set user [lindex $argv 1]
        set text [lindex $argv 2]
    }
    default {
        send_user "Usage: tlg <username> <text>\n"
        send_user "Usage: tlg </path/to/telegram/folder/> <username> <text>\n"
        exit 1
    }
}
spawn ${folder}telegram
sleep 2
expect ">"
send "msg $user $text\r"
expect "Sent"
send "quit\r"
expect eof
